// Generated by CoffeeScript 1.3.3
(function() {
  var ApplicationWindow;

  ApplicationWindow = function() {
    var FirstView, firstView, self;
    FirstView = require("ui/FirstView");
    self = Ti.UI.createWindow({
      backgroundColor: "#ffffff",
      navBarHidden: true,
      exitOnClose: true
    });
    firstView = new FirstView();
    self.add(firstView);
    return self;
  };

  module.exports = ApplicationWindow;

}).call(this);
