// Generated by CoffeeScript 1.3.3
(function() {
  var FirstView;

  FirstView = function() {
    var label, self;
    self = Ti.UI.createView();
    label = Ti.UI.createLabel({
      color: "#000000",
      text: String.format(L("welcome"), "Titanium"),
      height: "auto",
      width: "auto"
    });
    self.add(label);
    label.addEventListener("click", function(e) {
      return alert(e.source.text);
    });
    return self;
  };

  module.exports = FirstView;

}).call(this);
