/*! PROJECT_NAME - v0.1.0 - 2012-10-03
* http://PROJECT_WEBSITE/
* Copyright (c) 2012 hisasann; Licensed MIT */

// Generated by CoffeeScript 1.3.3
(function() {

  sample1(function() {
    var sample;
    sample = 'sample1';
    console.log(sample);
    return sample;
  });

}).call(this);

/*! PROJECT_NAME - v0.1.0 - 2012-10-03
* http://PROJECT_WEBSITE/
* Copyright (c) 2012 hisasann; Licensed MIT */

// Generated by CoffeeScript 1.3.3
(function() {

  sample2(function() {
    var sample;
    sample = 'sample2';
    console.log(sample);
    return sample;
  });

}).call(this);
